version: '3.3'
services:
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - webnet
  postgres:
    image: postgres:16
    volumes:
      - data-volume:/data/db
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - webnet
networks:
  webnet:
volumes:
  data-volume:
